# Generated by Django 5.1.5 on 2025-01-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='airport',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='logs.dataloadlog'),
        ),
    ]
